### ISSUE TITLE
TypesResolver - Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by theXappy** [theXappy/RemoteNET#2]
```
[Diver] Task faulted! Exception:
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at RemoteNET.Internal.Reflection.TypesResolver.Resolve(String assemblyName, String typeFullName)
   at RemoteNET.RemoteApp.GetRemoteType(String typeFullName, String assembly)
   at RemoteNET.RemoteApp.GetRemoteType(TypeDump typeDump)
   at RemoteNET.RemoteObject.GetType()
   at RemoteNET.Internal.DynamicRemoteObject..ctor(RemoteApp ra, RemoteObject ro)
   at RemoteNET.Internal.DynamicRemoteObjectFactory.Create(RemoteApp rApp, RemoteObject remoteObj, TypeDump typeDump)
   at RemoteNET.RemoteObject.Dynamify()
   at RemoteNET.Internal.DynamicRemoteObject.get_Item(Object key)
   at RemoteNET.RemoteHarmony.<>c__DisplayClass6_0.<WrapCallback>b__0(HookContext context, ObjectOrRemoteAddress instance, ObjectOrRemoteAddress[] args)
   at ScubaDiver.API.CallbacksListener.HandleDispatchedRequest(HttpListenerContext context)
   at ScubaDiver.API.CallbacksListener.<Dispatcher>g__ListenerCallback|19_0(IAsyncResult result)
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at RemoteNET.Internal.Reflection.TypesResolver.Resolve(String assemblyName, String typeFullName)
   at RemoteNET.RemoteApp.GetRemoteType(String typeFullName, String assembly)
   at RemoteNET.RemoteApp.GetRemoteType(TypeDump typeDump)
   at RemoteNET.RemoteObject.GetType()
   at RemoteNET.Internal.DynamicRemoteObject..ctor(RemoteApp ra, RemoteObject ro)
   at RemoteNET.Internal.DynamicRemoteObjectFactory.Create(RemoteApp rApp, RemoteObject remoteObj, TypeDump typeDump)
   at RemoteNET.RemoteObject.Dynamify()
   at RemoteNET.Internal.DynamicRemoteObject.get_Item(Object key)
   at RemoteNET.RemoteHarmony.<>c__DisplayClass6_0.<WrapCallback>b__0(HookContext context, ObjectOrRemoteAddress instance, ObjectOrRemoteAddress[] args)
   at ScubaDiver.API.CallbacksListener.HandleDispatchedRequest(HttpListenerContext context)
   at ScubaDiver.API.CallbacksListener.<Dispatcher>g__ListenerCallback|19_0(IAsyncResult result)
```

**Comment by theXappy** [comment]
Haven't occurred organicly in the last year. Closing for now.
