### ISSUE TITLE
Different processes won't share Injector_x64.exe nicely

### ISSUE THREAD

**Issue by theXappy** [theXappy/RemoteNET#4]
Indicated by this exception:
```
Loading...
ERROR: System.IO.IOException: The process cannot access the file 'C:\Users\*USER*\AppData\Local\RemoteNET\Injector_x64.exe' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at RemoteNET.RemoteApp.GetInjectionToolkit(Process target, String targetDotNetVer, String& remoteNetAppDataDir, String& injectorPath, String& scubaDiverDllPath)
   at RemoteNET.RemoteApp.Connect(Process target)
   at RemoteNET.RemoteApp.Connect(String target)
   at Program.DumpTypes(TypesDumpOptions opts) in C:\git\RemoteNetSpy\rnet-kit\rnet-dump\Program.cs:line 41

```

**Comment by theXappy** [comment]
Should be fixed now that the injector actually exists after the unmanged DLL quits
(Only the managed DLL stays loaded after a successful injection)
